### ISSUE TITLE
11 March 2021 - Cloud Service Certification Meeting

### ISSUE THREAD

**Issue by mcleo-d** [finos/cloud-service-certification#105]
## Date
Thursday 11 March 2021 - 10am EST / 3pm UK

## Untracked attendees
| Name | Firm | Comment |
|:---------|:------------|:-----|

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene, roll call, welcome new people (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://github.com/finos/community/blob/master/governance/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [x] Approve previous meeting minutes - https://github.com/finos/cloud-service-certification/issues?q=is%3Aissue+is%3Aclosed+label%3Ameeting
- [x] CDMC update from @mindthegab 
- [x] [CSC Agile Workflow](https://github.com/finos/cloud-service-certification/tree/master/docs/agile-workflow) and [Open Roles](https://github.com/finos/cloud-service-certification/tree/master/docs/open-roles) update from @peter-thomas-db  
- [x] AOB, Q&A & Adjourn (5mins)
- Cloud Service Certification [Project Kanban](https://github.com/orgs/finos/projects/1) Review

## Decisions Made
- [ ] ...

## Action Items
- [ ] ...

### WebEx info
**Webex:** 
https://finos.webex.com/finos/j.php?MTID=m4b1d85127d1f3ca179545d6bd3291975

**Dial-in**
- **US** +1-415-655-0003 US Toll
- **UK** +44-20319-88141 UK Toll
- **Access code:** 127 846 2278

**Github Repo:** https://github.com/finos/cloud-service-certification/

**Project Wiki Page:** https://finosfoundation.atlassian.net/wiki/spaces/FDX/pages/904626436/Cloud+Service+Certification+Project 

**Mailing List:** Email fdx-cloud-service-certification+subscribe@finos.org to subscribe to our mailing list

**Comment by mcleo-d** [comment]
Updates from @J0EG via email ...

1) I changed the format to asciidoc, silly enough it took longer than expected for some reason none of the converters captured the formatting. You should have the latest pull request for that commit. 

2) Also made some content changes, but there is still white space to fill in, so i'm still iterating the updates.

3) As mentioned, we are working to resource this effort more comprehensively, we have a meeting late next week to discuss.

**Comment by eddie-knight** [comment]
:wave: :shipit:

**Comment by peterrhysthomas** [comment]
hello everyone

**Comment by mcleo-d** [comment]
Hello 👋

**Comment by cr20ro20** [comment]
Hi

**Comment by jamilmina1** [comment]
Good day

**Comment by njwilliams** [comment]
hi

**Comment by bstone-suse** [comment]
Hello all.

**Comment by leefaus** [comment]
👋🏻  🎉

**Comment by bstone-suse** [comment]
Don't understand - that's my username @bstone-suse should be any issue.

**Comment by mcleo-d** [comment]
> Don't understand - that's my username @bstone-suse should be any issue.

Hi @bstone-suse

Thanks for your response. The message is from the FINOS roll call GitHub Action letting the FINOS team know this is the first meeting you have attended. There's nothing to be concerned about, but thanks for calling it out.

Speak soon.

James.
