### ISSUE TITLE
Evolving CSC Team Roles, Agile Ceremonies and Sprint Cadence

### ISSUE THREAD

**Issue by mcleo-d** [finos/cloud-service-certification#106]
## Description
As Cloud Service Certification scales, attracts pull requests and gains momentum, this issue addresses evolving CSC team roles, agile ceremonies and sprint cadence in response to feedback from the CSC project and community.

## Related Pull Requests
- Update project README with CSC logo and CSC wiki homepage content  #95
- Remove Cloud Service Certification Roles No Longer Needed  #100
- Add Cloud Service Certification Project Maintainer Role  #103
- Add Cloud Service Certification Project Operations Manager Role #99

**Comment by peter-thomas-db** [comment]
Here are some initial thoughts from me

- Run the project like a scrum/agile project with sprint cadence, standup, planning ,demo, etc
- Monthly (for example) sprints, using end of month session for sprint review/demo and planning for next sprint
- Volunteers would form a sub-team around a task
- Outside of session, sub-team swarm around tasks with self-organised sessions (similar to how Eddie/Lee have been progressing the testing task)
- Mid-month session would be standup for updates from the sub-teams and a point for any other discussions and demo if any work had been completed so far
- Sub-team would collectively review and approve their own work, with final review and merge performed by a maintainer at end of sprint
- Quarterly (for example) high level planning of strategy for next quarter which would then break down into sprint priorities.

**Comment by mcleo-d** [comment]
@peter-thomas-db - I have started the work in progress document in the comment below before raising as a PR. 

Please feel free to edit the comment directly or leave comments below ...

**Comment by mcleo-d** [comment]
# Cloud Service Certification - Agile Workflow

The Agile Workflow for Cloud Service Certification falls into two main work streams which are overseen by Cloud Service Certificaton Maintainers and fulfilled by the CSC project team and wider FINOS community.

- [Agile Delivery of Prioritised Work Items](#agile)
- [Community Contributions and Pull Requests](#community)

## <a name="agile">Agile Delivery of Prioritised Work Items</a>

- The Cloud Service Certification project is run as an agile project with agile ceremonies and a fixed sprint cadence. Example agile ceremonies include ...
  - Regular team stand-ups
  - Agreed sprint cadence
  - Maintainer and team backlog grooming
  - Pre-sprint planning sessions
  - End of sprint team demos

- **Two Week** or **Monthly** sprints, as agreed with the CSC project, using end of sprint sessions for team demos and planning for next sprint.
- Volunteers form sub-teams around given tasks, epics or stories. The sub-team owns the delivery, and method of delivery from start to finish.
- Sub-teams swarm around tasks with self-organised team sessions at the discression and independent management of the team.
- Mid-month project sessions act as standups for sub-team updates and a point for any other discussions and demos to demonstrate completed work or where blockers need to be removed.
- Sub-teams collectively review and approve their own work, with final review and merge performed by the maintainer team at the end of sprint.
- Quarterly (for example) high level planning of roadmap for next quarter, half and year ahead which then breaks down into sprint priorities.

## <a name="community">Community Contributions and Pull Requests</a>
