### ISSUE TITLE
First release of Cloud Service Certification Artefacts

### ISSUE THREAD

**Issue by mcleo-d** [finos/cloud-service-certification#12]
### Description of Problem:
To accelerate the Cloud Service Certification OSS team, the first swathe of Cloud Service Certification artefacts should be contributed to the project.

### Potential Solutions:
The contributed artefacts should be items that clearly demonstrate the direction of the project, such as cookbooks, infrastructure as code, BDD scripts and other items of value.

The artefacts should be tested and their functionality should be utilised by the community to allow team members to replicate, demonstrate and extend their functionality.

When the artefacts have been added, an agenda item should be added to the team group call to review, hand over and invite group feedback.

**Comment by git-hub-forwork1** [comment]
Several artifacts have been contributed for a few AWS cloud services.  It is important to get feedback on those artifacts and discuss how contribution and participation among project members can be achieved.

**Comment by mcleo-d** [comment]
Thanks for the contribution @git-hub-forwork1 - The CSC project has agreed to review once there is an internal banking need to consume the material. Feel free to suggest a project team that's able to consume and feedback as part of the group.
