### ISSUE TITLE
20 May 2021 - Cloud Service Certification Project Meeting - Mid Sprint 2 Review

### ISSUE THREAD

**Issue by mcleo-d** [finos/cloud-service-certification#120]
## Date
Thursday 20 May 2021 - 10am EST / 3pm BST

## Untracked attendees
| Name | Firm | Comment |
|:---------|:------------|:-----|

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene, roll call, welcome new people (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://github.com/finos/community/blob/master/governance/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [x] Approve previous meeting minutes - https://github.com/finos/cloud-service-certification/issues?q=is%3Aissue+is%3Aclosed+label%3Ameeting
- [ ] Cloud Service Certification - Mid Sprint 2 Review - [Sprint 2 Project Kanban](https://github.com/orgs/finos/projects/1#column-13982219)
  - **Sprint Backlog** 
    - Functional and Declarative BDD Testing Examples #62 - @leefaus
    - Group Discussion : CIS Benchmarks, BDD Testing and Tools Provisioning #84 - @leefaus / @eddie-knight
    - Rename CSC primary branch to follow best practices #119  - @TLATER
  - **In Progress**
    - adding some policies for conftest #91 - @leefaus
  - **Ready for Review**
    - EKS - Terraform #113 - @abdullahgarcia / @njwilliams
    - Adding structure expectations to CONTRIBUTING.md #102 @eddie-knight
    - Red Hat OpenShift Container Platform Service Approval Accelerator #97 - @J0EG
- [ ] @mindthegab - FINOS / CDMC / EDMC Partnership Conversation **(25 mins required)**
- [ ] AOB, Q&A & Adjourn

## Decisions Made
- [ ] ...

## Action Items
- [ ] ...

### WebEx info
**Webex:** 
https://finos.webex.com/finos/j.php?MTID=m4b1d85127d1f3ca179545d6bd3291975

**Dial-in**
- **US** +1-415-655-0003 US Toll
- **UK** +44-20319-88141 UK Toll
- **Access code:** 127 846 2278

**Github Repo:** https://github.com/finos/cloud-service-certification/

**Project Wiki Page:** https://finosfoundation.atlassian.net/wiki/spaces/FDX/pages/904626436/Cloud+Service+Certification+Project 

**Mailing List:** Email fdx-cloud-service-certification+subscribe@finos.org to subscribe to our mailing list

**Comment by eddie-knight** [comment]
@mcleo-d asked me to give an update on the status of Probr & the ability to integrate it into the CSC pipeline :shipit:

**Comment by eddie-knight** [comment]
@mcleo-d Please allow me to discuss this issue regarding CI with the team as well: https://github.com/finos/cloud-service-certification/issues/124

**Comment by mcleo-d** [comment]
@eddie-knight - I have added the Probr update as a note to the Sprint 2 kanban for Thursday's meeting. See below ...
https://github.com/orgs/finos/projects/1#card-61420701

> @mcleo-d asked me to give an update on the status of Probr & the ability to integrate it into the CSC pipeline :shipit:

**Comment by mcleo-d** [comment]
@eddie-knight - #124 is on the project kanban, so can be updated as part of the meeting format. I hope that works?
https://github.com/orgs/finos/projects/1#card-61346419

> @mcleo-d Please allow me to discuss this issue regarding CI with the team as well: #124

**Comment by TLATER** [comment]
o/

**Comment by mcleo-d** [comment]
Hello 👋

**Comment by anthonygtech** [comment]
Hello.

**Comment by peterrhysthomas** [comment]
Hi everyone 🤖

**Comment by abdullahgarcia** [comment]
¡Hola!

**Comment by leefaus** [comment]
Hello -- 🥇

**Comment by J0EG** [comment]
Good Morning

**Comment by smarunich** [comment]
Hi Everyone

**Comment by eddie-knight** [comment]
:wave: :shipit:

**Comment by mcleo-d** [comment]
Hello 👋

**Comment by jgavronsky** [comment]
Jane here

**Comment by iantivey** [comment]
Hello
