### ISSUE TITLE
AWS EKS Terraform Review and Feature Input

### ISSUE THREAD

**Issue by mcleo-d** [finos/cloud-service-certification#123]
## Description

This issue requests a [AWS EKS Terraform](https://github.com/finos/cloud-service-certification/tree/master/aws/eks/eks-terraform-scripts) review (commit https://github.com/finos/cloud-service-certification/commit/9e9ec68bc8242b69152cf2258c401fcd5b738f32) and feature input from the Cloud Service Certification and wider open source community following the merge of #113 by @peterrhysthomas and @abdullahgarcia. 

During the #113 review, @peterrhysthomas asked if @TLATER or @alfredtommy could review the [AWS EKS Terraform Scripts](https://github.com/finos/cloud-service-certification/tree/master/aws/eks/eks-terraform-scripts) against the similar AKS / GKE scripts for [Azure](https://github.com/finos/cloud-service-certification/tree/master/azure/aks) and [GCP](https://github.com/finos/cloud-service-certification/tree/master/gcp/gke/gke-terraform-scripts).

## EKS PR Review Notes
https://github.com/finos/cloud-service-certification/pull/113#pullrequestreview-660917765

> This looks good to me, it would be good to get a comparison of this versus the GKE for Azure and GCP so if @TLATER or @alfredtommy to see if there is anything they think of note - @mcleo-d will create a new issue for enhancements to this which can be used for anything we would like to add afterwards.

## Moving forward

1. Review `AWS EKS Terraform` commit https://github.com/finos/cloud-service-certification/commit/9e9ec68bc8242b69152cf2258c401fcd5b738f32 and make inline improvement suggestions against the relevant line number.
2. Make suggestions for further improvements / features to this issue for further backlog grooming with the Cloud Service Certification community.

**Comment by TLATER** [comment]
There currently are no terraform skripts for Azure yet, not sure if that means everything or nothing is different ;)

I imagine the EKS scripts will be used as a template for any future implementation, simply because it sets precedent, so I'm not too concerned that it won't match. I'll keep an eye out though.

**Comment by mcleo-d** [comment]
Hey @TLATER 👋 

Please cast your eyes over if you get a chance as it would be great to see if anything stands out. I understand your domain knowledge is Azure, but you never know! 😁 

James 🚀

**Comment by mcleo-d** [comment]
Hi @abdullahgarcia,

I have extended CSC Sprint 2 until 17th June '21 due to team member annual leave and have added this item to the #127 agenda to discuss in relation to completion and Sprint 3.

Cheers,

James 🚀

**Comment by mcleo-d** [comment]
..

**Comment by mcleo-d** [comment]
Adding to prioritised for Sprint 4 for @njwilliams to allocate to Morgan Stanley AWS EKS engineers to review.

**Comment by peterrhysthomas** [comment]
@cphang99 to perform offline review and feedback any comments

**Comment by abdullahgarcia** [comment]
@cphang99 , I've seen your review and comments. 

I've replied to them too.

If possible, let's have a catch up this week.

**Comment by mcleo-d** [comment]
The latest PR raised as a result of this issue is #141 between @cphang99 and @abdullahgarcia.

Closing this issue.

**Comment by mcleo-d** [comment]
Thank you everyone 🚀
