### ISSUE TITLE
3 June 2021 - Cloud Service Certification Project Meeting - End of Sprint 2 🏁

### ISSUE THREAD

**Issue by mcleo-d** [finos/cloud-service-certification#126]
## Date
Thursday 3 June - 10am EST / 3pm BST

## Untracked attendees
| Name | Firm | Comment |
|:---------|:------------|:-----|

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [ ] Convene, roll call, welcome new people (5mins)
- [ ] Display [FINOS Antitrust Policy summary slide](https://github.com/finos/community/blob/master/governance/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [ ] Review Meeting Notices (see above)
- [ ] Approve previous meeting minutes - https://github.com/finos/cloud-service-certification/issues?q=is%3Aissue+is%3Aclosed+label%3Ameeting
- [ ] Cloud Service Certification End of Sprint 2 - [Project Kanban](https://github.com/orgs/finos/projects/1) 
  - **Sprint 2 Backlog**
    - Github Action for Terraform Checks #124 - @eddie-knight / @abdullahgarcia 
    - Functional and Declarative BDD Testing Examples #62 - @leefaus
    - AWS EKS Terraform Review and Feature Input #123 - @abdullahgarcia 
  - **In Progress**
    - adding some policies for conftest #91 - @leefaus
    - Red Hat OpenShift Container Platform Service Approval Accelerator #97 - @J0EG
  - **Ready for Review**
    - Rename CSC primary branch to follow best practices #119 - @TLATER  / @maoo (https://github.com/finos/cloud-service-certification/issues/126#issuecomment-849560919)
  - **Done**
    - Probr update note - @eddie-knight 
    - Adding structure expectations to CONTRIBUTING.md - #102 - @eddie-knight - PR Merged! 👏🏻 💯 💯 💯 
- [ ] Prioritise and Start Sprint 3 - https://github.com/orgs/finos/projects/1#column-14492299
- [ ] AOB, Q&A & Adjourn (5mins)

## Decisions Made
- [ ] Decision 1

## Action Items
- [ ] Action 1

### WebEx info
**Webex:** 
https://finos.webex.com/finos/j.php?MTID=m4b1d85127d1f3ca179545d6bd3291975

**Dial-in**
- **US** +1-415-655-0003 US Toll
- **UK** +44-20319-88141 UK Toll
- **Access code:** 127 846 2278

**Github Repo:** https://github.com/finos/cloud-service-certification/

**Project Wiki Page:** https://finosfoundation.atlassian.net/wiki/spaces/FDX/pages/904626436/Cloud+Service+Certification+Project 

**Mailing List:** Email fdx-cloud-service-certification+subscribe@finos.org to subscribe to our mailing list

**Comment by mcleo-d** [comment]
Hi @maoo 👋🏻 

Are you able to attend Cloud Service Certification on 3rd June at 3pm BST / 10am?

@TLATER has created recommendations for **Rename CSC primary branch to follow best practices** #119 which needs FINOS infrastructure review, prioritisation and involvement. 

This issues is intended to move https://github.com/finos/community/issues/114 forward by creating a tested pattern for other FINOS projects to follow.

**Comment by maoo** [comment]
> Hi @maoo 👋🏻
> 
> Are you able to attend Cloud Service Certification on 3rd June at 3pm BST / 10am?

Sure, count me in! 👍

**Comment by TLATER** [comment]
o/

**Comment by agitana** [comment]
hi!

**Comment by fleadsom** [comment]
hey!

**Comment by maoo** [comment]
👋

**Comment by RichardWagener365** [comment]
Hi! - Richard Wagener - Codethink

**Comment by alfredtommy** [comment]
hello

**Comment by cr20ro20** [comment]
Hi - Craig Rowe

**Comment by jgavronsky** [comment]
Jane here
