### ISSUE TITLE
1 July 2021 - Cloud Service Certification Project Meeting - Mid Sprint 3 Review

### ISSUE THREAD

**Issue by mcleo-d** [finos/cloud-service-certification#130]
## Date
Thursday 1st July 2021 - 10am EST / 3pm BST

## Untracked attendees
| Name | Firm | Comment |
|:---------|:------------|:-----|

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene, roll call, welcome new people (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://github.com/finos/community/blob/master/governance/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [x] Approve previous meeting minutes - https://github.com/finos/cloud-service-certification/issues?q=is%3Aissue+is%3Aclosed+label%3Ameeting
- [ ] Cloud Service Certification - Mid Sprint 3 Review - [Sprint 3 Project Kanban](https://github.com/orgs/finos/projects/1#column-14492299)
  - **Sprint Backlog**
    - Rename CSC primary branch to follow best practices #119 - @TLATER 
    - OpenShift Kubernetes Definition #92 - @J0EG
    - Add CI for terraform fmt #117 - @peterrhysthomas
    - adding some policies for conftest #91 - @leefaus
    - Group Discussion : CIS Benchmarks, BDD Testing and Tools Provisioning #84 - @mcleo-d 
    - Github Action for Terraform Checks #124 - @eddie-knight / @abdullahgarcia 
    - AWS EKS Terraform Review and Feature Input #123 - @abdullahgarcia 
    - Functional and Declarative BDD Testing Examples #62 - @leefaus
    - Document Pre- and Post- Deployment Automated Checks #128 - @eddie-knight 
  -  **In Progress**
     - README: Make absolute links to the master branch relative #129 - @TLATER 
  - **Ready for Review**
    - _Zero_
  - **Done**
    - _Zero_ 
- [x] AOB, Q&A & Adjourn (5mins)
  - [x] Morgan Stanley update - @njwilliams

## Decisions Made
- [ ] ...

## Action Items
- [ ] ...

### WebEx info
**Webex:** 
https://finos.webex.com/finos/j.php?MTID=m4b1d85127d1f3ca179545d6bd3291975

**Dial-in**
- **US** +1-415-655-0003 US Toll
- **UK** +44-20319-88141 UK Toll
- **Access code:** 127 846 2278

**Github Repo:** https://github.com/finos/cloud-service-certification/

**Project Wiki Page:** https://finosfoundation.atlassian.net/wiki/spaces/FDX/pages/904626436/Cloud+Service+Certification+Project 

**Mailing List:** Email fdx-cloud-service-certification+subscribe@finos.org to subscribe to our mailing list

**Comment by TLATER** [comment]
o/

**Comment by njwilliams** [comment]
aloha

**Comment by abdullahgarcia** [comment]
¡Hola!

**Comment by peterrhysthomas** [comment]
hello

**Comment by RichardWagener365** [comment]
Hi there

**Comment by anthonygtech** [comment]
hello.

**Comment by lpaul1** [comment]
Great meeting. - Nice progress so far.
