### ISSUE TITLE
7 October 2021 - Cloud Service Certification Project Meeting

### ISSUE THREAD

**Issue by mcleo-d** [finos/cloud-service-certification#142]
## Date
Thursday 7 October - 10am EST / 3pm BST

## Untracked attendees
| Name | Firm | Comment |
|:---------|:------------|:-----|

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene, roll call, welcome new people (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://github.com/finos/community/blob/master/governance/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [x] Approve previous meeting minutes - https://github.com/finos/cloud-service-certification/issues?q=is%3Aissue+is%3Aclosed+label%3Ameeting
- [x] Cloud Service Certification [Project Kanban](https://github.com/orgs/finos/projects/1) Review
- [ ] Review CSC output of @peter-thomas-db session at FINOS Member Meeting, London
- [ ] Question : How can we accelerate the AWS EKS SDLC through GitHub Actions to enable @eddie-knight and Probr ?
- [ ] Well done @abdullahgarcia for winning the **FINOS Coaching Award** for work done on Cloud Service Certification 👏🏻 💯 💯 💯 
- [x] AOB, Q&A & Adjourn (5mins)
  - [x] Changing the date and time of CSC meetings ... https://github.com/finos/cloud-service-certification/issues/142#issuecomment-937761391 

## Decisions Made
- [ ] ...

## Action Items
- [ ] ...

### WebEx info
**Webex:** 
https://finos.webex.com/finos/j.php?MTID=m4b1d85127d1f3ca179545d6bd3291975

**Dial-in**
- **US** +1-415-655-0003 US Toll
- **UK** +44-20319-88141 UK Toll
- **Access code:** 127 846 2278

**Github Repo:** https://github.com/finos/cloud-service-certification/

**Project Wiki Page:** https://finosfoundation.atlassian.net/wiki/spaces/FDX/pages/904626436/Cloud+Service+Certification+Project 

**Mailing List:** Email fdx-cloud-service-certification+subscribe@finos.org to subscribe to our mailing list

**Comment by timretout** [comment]
Possible AOB item: I would be interested to hear a brief update on what went on at the Member meeting on 4th Oct, if this is possible!

**Comment by eddie-knight** [comment]
Saw my name tagged here! My schedule recently hasn't allowed me to attend the calls, but I'm still available via email and slack if there is anything I can help with.

**Comment by mcleo-d** [comment]
Thanks @eddie-knight 👍🏻 

Can you add a date and time that works for you as @peter-thomas-db is also having the same issue and we're thinking of changing the meeting to suit.

I'm going to raise as AOB today.

**Comment by RichardWagener365** [comment]
Hi

**Comment by TLATER** [comment]
o/
