### ISSUE TITLE
Can the work produced by the Cloud Security Alliance be brought into or shared across FINOS firms?

### ISSUE THREAD

**Issue by mcleo-d** [finos/cloud-service-certification#17]
### Description
As raised on the Cloud Service Certification call on 30th January 2020 : Can the work produced by the Cloud Security Alliance be brought into or shared across FINOS firms?

Raised by @abdullahgarcia

**Comment by git-hub-forwork1** [comment]
I spoke to @abdullahgarcia about this question and I believe the intent was to determine if the content created by this project would feed into larger projects like CSA.  
This is something that is always possible as this project is open source and making our work more known by it being consumed by a larger project is fine.  
However,  seeing the CSA content and working with it in the past as most of us have, we realize that our project content fits into a more implementation level detail that is more prescriptive in nature.  I would see our project content being a reference from CSA and other projects like it more than a feeder into the larger projects.
