### ISSUE TITLE
DEPRECATED ISSUE : 7 May 2020 - Cloud Service Certification Meeting Minutes

### ISSUE THREAD

**Issue by mcleo-d** [finos/cloud-service-certification#29]
## Date
Thursday 07 May 2020 - 10am EST

## Untracked attendees
- ...

## Agenda
- [ ] Convene, roll call, welcome new people **(5 min)** - @git-hub-forwork1 
- [ ] Review action items from previous meetings (see above) **(5 min)** - @git-hub-forwork1 
- [ ] Cloud Service Certification Kanban Review **(20 min)** - @git-hub-forwork1 
  - Let's review the CSC kanban to make sure the right items are in play and reflected correctly. 
  - **Action Items**
    - As recorded in this GitHub Issue
  - **In Progress**
    - https://github.com/finos/cloud-service-certification/issues/16
    - https://github.com/finos/cloud-service-certification/issues/18
    - https://github.com/finos/cloud-service-certification/issues/12
  - **Prioritised** 
    - https://github.com/finos/finos-pmcs/issues/19
      - Relates to : https://github.com/finos/cloud-service-certification/issues/11
    - https://github.com/finos/cloud-service-certification/issues/13
    - https://github.com/finos/cloud-service-certification/issues/23
- [ ] CSC project team reviewing code contributions and pull requests **(15 min)** - @git-hub-forwork1 
  - It's been raised by the project we need a method of review contributions and pull requests that equally spans all project members. This item has been added to discuss next steps for creating a group of moderators.
- [ ] Cloud Service Certification Group Review of CitiHub Compliance as Code GitHub Project **(10 min)**
  - **Freedie Leadsom**, **Daniella Zheleva** and **Peter Thomas** from Deutsche Bank feedback following CitiHub project review with **Matt Gall** and **Ian Tivey** from CitiHub - Action taken at [2020-04-23 Cloud Service Certification Project Meeting](https://finosfoundation.atlassian.net/wiki/spaces/FDX/pages/1569226806/2020-04-23+Cloud+Service+Certification+Project+Meeting)
  - https://github.com/citihub/compliance-as-code-whitepaper 
- [ ] AOB & adjourn **(5 min)** - @git-hub-forwork1 

## Decisions Made
- [ ] Decision 1
- [ ] Decision 2
- [ ] ...

## Action Items
- [ ] Ian Tivey to talk to CitiHub clients about joining Cloud Service Certification and their use of Kubernetes
- [ ] James McLeod to introduce Freddie Leadsom to the FINOS Open Source Readiness Project
- [ ] James McLeod to coordinate - Peter Thomas suggested connecting with Matt Gall to align methodologies, as the CitiHub team are advising a different area of Deutsche Bank.
- [ ] James McLeod to coordinate - Peter Thomas would like suggestions on what would be useful to contribute to FINOS.
- [ ] James McLeod to coordinate - Jamil Mina suggests Red Hat conduct a session where the Red Hat team can help answer how to commoditise open source software.

### WebEx info
**Webex:** 
https://finos.webex.com/finos/j.php?MTID=me0b8e6061812f875505b0caaceac3321

**Dial-in**
+1-415-655-0003 US Toll
+44-20319-88141 UK Toll
Access code: 662 732 581

**Github Repo:** https://github.com/finos-fdx/cloud-service-certification/
**Project Wiki Page:** https://finosfoundation.atlassian.net/wiki/spaces/FDX/pages/904626436/Cloud+Service+Certification+Project

**Comment by JamesWrightesq** [comment]
Hello!

**Comment by mcleo-d** [comment]
This meeting was deprecated due to ODP GitHub Action integration/test and can be found here #32
