### ISSUE TITLE
OSSF presence

### ISSUE THREAD

**Issue by jbjonesjr** [finos/cloud-service-certification#3]
@finos/fdx-cloud-cert and @git-hub-forwork1 (lol), related to https://github.com/finos/finos-pmcs/issues/5 , what is our larger OSSF strategy? Meeting? Booth? General session?

Figure we can get the conversation started here.

**Comment by git-hub-forwork1** [comment]
I think this has been addressed via panel and presentation activities.  Let me know if further action is needed.

**Comment by mcleo-d** [comment]
@jbjonesjr and @git-hub-forwork1 - Closing issue as no direct action and historic request.

**Comment by jbjonesjr** [comment]
thank you @mcleo-d and good job on stage @git-hub-forwork1
