### ISSUE TITLE
21 May 2020 - Cloud Service Certification Meeting

### ISSUE THREAD

**Issue by mcleo-d** [finos/cloud-service-certification#34]
## Date
Thursday 21 May 2020 - 10am EST

## Untracked attendees

* Abdullah Garcia - JPMC

## Agenda

- [x] **1.** Convene, roll call, welcome new people
- [x] **2.** Review action items from previous meetings
- [x] **3.** Coordinate with Deutsche Bank and CitiHub regarding bringing coordinated activity into the open
- [x] **4.** Report outcome of the following action item to the group (@git-hub-forwork1) 
  - "_Coordinate meeting with @git-hub-forwork1 to add more CSS project leads and maintainers to the project_"
- [x] **5.** Share FINOS [Project Collaboration on Github](https://finosfoundation.atlassian.net/wiki/spaces/FDX/pages/75530554/Project+Collaboration+on+Github#ProjectCollaborationonGithub-AccessControl) and [Contribution Compliance Requirements](https://finosfoundation.atlassian.net/wiki/spaces/FINOS/pages/75530375/Contribution+Compliance+Requirements) with the group (@mcleo-d) 
- [x] **6.** Group Question : Is the following activity something that should be conducted immediately or queued up for the future? (@git-hub-forwork1)
  - Coordinate with @jamilmina1 on Red Hat cloud service classifications and adding Kubernetes activity to the agenda
- [x] **7.** AOB, Q&A & Adjourn

## Decisions Made

* Jason to liaise with Peter, Freddie and Daniela at DB to coordinate standard contribution structure across banks.
* DB ready to contribute and need to decide how this should happen with Jason and the JPMC team.
* This can be done amongst banking teams and then rolled out further to the group.
* Item 6 : 
  * **Team decision not to focus on Kubernetes**
  * DB not using Kubernetes at the moment and is focusing on Azure. 
  * JPMC have open sourced Kubernetes material and believe this shouldn't be an immediate focus for now. This is not the focus area of Cloud Service Certification.
  * Wipro not in a position to comment at the moment without team input. Will ask the team and revert. 
  * Red Hat agree on the comments above.
* Item 4 :
  * **Group Agreement** DB will work with JPMC to formalise the structure, focus and direction of Cloud Service Certification as they draw closer to contributing into Cloud Service Certification.

## Open Action Items
- [x] Coordinate with Deutsche Bank and CitiHub regarding bringing coordinated activity into the open
- [x] Coordinate with @jamilmina1 on Red Hat cloud service classifications and adding Kubernetes activity to the agenda
- [x] Share FINOS [Project Collaboration on Github](https://finosfoundation.atlassian.net/wiki/spaces/FDX/pages/75530554/Project+Collaboration+on+Github#ProjectCollaborationonGithub-AccessControl) and [Contribution Compliance Requirements](https://finosfoundation.atlassian.net/wiki/spaces/FINOS/pages/75530375/Contribution+Compliance+Requirements) with the group.

## Action Items
* CSC group to review, comment raise PRs on the following template ahead of the next project call 
  * https://github.com/finos/cloud-service-certification/blob/master/templates/ServiceApprovalAcceleratorTemplate.md

## Questions Raised
* DB asks how are JPMC organising their branching strategy in order to engage with Cloud Service Certification?
  * @brooklynrob notes JPMC have FINOS projects whitelisted for FINOS contribution.

### WebEx info
**Webex:** 
https://finos.webex.com/finos/j.php?MTID=me0b8e6061812f875505b0caaceac3321

**Dial-in**
**US** +1-415-655-0003 US Toll
**UK** +44-20319-88141 UK Toll
**Access code:** 662 732 581

**Github Repo:** https://github.com/finos-fdx/cloud-service-certification/
**Project Wiki Page:** https://finosfoundation.atlassian.net/wiki/spaces/FDX/pages/904626436/Cloud+Service+Certification+Project

**Comment by mcleo-d** [comment]
👋 hello!

**Comment by git-hub-forwork1** [comment]
Hello

**Comment by fleadsom** [comment]
hi

**Comment by danizheleva** [comment]
Hello

**Comment by jamilmina1** [comment]
Hello

**Comment by alfredtommy** [comment]
Hi

**Comment by git-hub-forwork1** [comment]
@abdullahgarcia here as well

**Comment by adamtrousdale** [comment]
Hello

**Comment by alavi1999** [comment]
hey

**Comment by brooklynrob** [comment]
here

**Comment by mcleo-d** [comment]
After an offline conversation with @jamilmina1, **Item 6** under **Decisions Made** has been changed to better reflect Red Hat's detailed position...

> _Red Hat acknowledges that there is no demand for Kube in this group at the moment though Red Hat may continue to use Kube as an underlying implementation for other services._
