### ISSUE TITLE
4 June 2020 - Cloud Service Certification Meeting

### ISSUE THREAD

**Issue by mcleo-d** [finos/cloud-service-certification#35]
## Date
Thursday 4th June 2020 - 10am EST / 3pm BST

## Untracked attendees
- Madhuri Racherla, Morgan Stanley 
- Ricardo Oneda, Itau
- Dominic Dumrauf, Citihub
- Eric Tice, Wipro

## Agenda
- [x] Convene, roll call, welcome new people
- [x] Review action items from previous meetings
- [x] Update on Searce representing Google Cloud Platform contributions from meeting between @git-hub-forwork1, @peterrhysthomas, @pudern, @alfredtommy and @mcleo-d 
- [x] Group discussion, feedback and review of the [Service Approval Accelerator Template](https://github.com/finos/cloud-service-certification/blob/master/templates/ServiceApprovalAcceleratorTemplate.md) following CSC action during #34
  - @git-hub-forwork1 chairing **Amazon Web Services**
  - @peterrhysthomas chairing **Microsoft Azure**
    - https://github.com/finos/cloud-service-certification/issues/35#issuecomment-638836705
  - @alfredtommy chairing **Google Cloud Platform**
- [x] AOB, Q&A & Adjourn

## Open Action Items
- [x] CSC group to review, comment raise PRs on the following template ahead of the next project call
  - https://github.com/finos/cloud-service-certification/blob/master/templates/ServiceApprovalAcceleratorTemplate.md

## Actions
- [ ] @danizheleva to incorporate **Service Approval Accelerator Template** suggestions in https://github.com/finos/cloud-service-certification/issues/35#issuecomment-638836705 into https://github.com/finos/cloud-service-certification/blob/master/templates/ServiceApprovalAcceleratorTemplate.md with @git-hub-forwork1 via pull request. 
- [ ] @git-hub-forwork1 and @peterrhysthomas to coordinate tidying https://github.com/finos/cloud-service-certification/blob/master/templates/ServiceApprovalAcceleratorTemplate.md to remove technology references to enable white labelling for multiple service types.
- [ ] @iantivey to review https://github.com/finos/cloud-service-certification/blob/master/templates/ServiceApprovalAcceleratorTemplate.md and feedback into the comments of this issue if required. 
- [ ] @mcleo-d to review CSC meeting and capture decisions / actions and add to this issue. 

### WebEx info
**Webex:** 
https://finos.webex.com/finos/j.php?MTID=me0b8e6061812f875505b0caaceac3321

**Dial-in**
**US** +1-415-655-0003 US Toll
**UK** +44-20319-88141 UK Toll
**Access code:** 662 732 581

**Github Repo:** https://github.com/finos/cloud-service-certification/
**Project Wiki Page:** https://finosfoundation.atlassian.net/wiki/spaces/FDX/pages/904626436/Cloud+Service+Certification+Project

**Comment by danizheleva** [comment]
Hi everyone,

We have done some work to review Service Approval Accelerator Template. Since we cannot raise a PR with proposed structure change, I am posting on here for visibility for the group. 

Overall there was a good overlap with the information in the template and the categories we have looked at for Azure services. Some changes could perhaps be to add some extra detail to the table in the document in the following way: 

1. Proposed structure of template:
    - Identity and Access Management
    - Authentication
    - Authorization
    - RBAC
    - Privileged Access Management
2. Encryption & Secure Data Management
    - Encryption in transit
    - Encryption at rest
    - Certificate and Key Management
    - BYOK/HYOK Management
3. Network Security
    - Endpoint localisation
    - IP Firewall rules
    - Data exfiltration prevention
4. Logging and Monitoring
    - Security monitoring & Audit
    - Service Monitoring
    - Alert and incident management
5. Resilience and Recovery
    - Data resilience (back ups/ replication)
    - Compute high availability
6. External Certification (?) <- unsure what is meant by this
7. Underlying OS (?) <- unsure what is meant by this
8. CSP access
9. Dependent Services

Posting on here so we can discuss in more detail on the call.

**Comment by mcleo-d** [comment]
Thanks @danizheleva - I've linked to the comment above in the agenda of today's call 👍

**Comment by git-hub-forwork1** [comment]
Hello

**Comment by danizheleva** [comment]
Hello

**Comment by jamilmina1** [comment]
Hi

**Comment by abdullahgarcia** [comment]
Hi!

**Comment by alfredtommy** [comment]
Hello

**Comment by fleadsom** [comment]
Hello

**Comment by junjikatto** [comment]
hi!

**Comment by anthonygtech** [comment]
hi

**Comment by knewcomerRH** [comment]
Hi

**Comment by dschwartznyc** [comment]
Hello fr daniel.schwartz@ftadvisory.co

**Comment by mikejstevenson** [comment]
Hello!

**Comment by peterrhysthomas** [comment]
hello

**Comment by mcleo-d** [comment]
Hello 👋

**Comment by pudern** [comment]
hello!

**Comment by iantivey** [comment]
Hi

**Comment by alavi1999** [comment]
hi

**Comment by alfredtommy** [comment]
My suggestion for additional categories in the template:
1) DLP (covered by Daniela as data exfiltration) -> under network security or encryption/data masking
2) CSP support for latest secure/stable version of software -> independent category

**Comment by dumrauf** [comment]
Hi
