### ISSUE TITLE
Delivery of Google Kubernetes Engine (GKE) Service for GCP including Security Command Center

### ISSUE THREAD

**Issue by alfredtommy** [finos/cloud-service-certification#44]
### Description 
@pudern and @alfredtommy from Searce to create, lead and deliver a Cloud Service Certification service that introduces and demonstrates GCP Security Command Center Service to CSC.

### Success Criteria
- [x] Create an issue that describes introducing and demonstrating the GCP Security Command Center Service to the CSC project.
- [x] Decide on a single GCP service use case that's similar to current CSC AWS and Azure focus.
- [x] Contribution to focus on **Google Kubernetes Engine (GKE)** Service - https://cloud.google.com/kubernetes-engine/docs/concepts/kubernetes-engine-overview
- [ ] Demonstrate through contributed code, configuration and integration examples how Security Command Center Service capabilities deliver CSC security and compliance requirements.
- [ ] Demonstrate through code contribution how GCP services contributed to CSC run anywhere as reusable artefacts.
- [ ] Raise a pull request for the first GCP service contribution into Cloud Service Certification that also includes [ServiceApprovalAcceleratorTemplate.md](https://github.com/finos/cloud-service-certification/blob/master/templates/ServiceApprovalAcceleratorTemplate.md)  🎉 

## New Cloud Service Request

A new cloud service must follow the standard completion template. The 'definition of done' of a cloud service request is defined as follows:

- [x] Cloud Platform Target - **Google Cloud Platform**

The directory in which the Cloud Service will reside (/<cloud_platform>/<service_name>).
- [x] Service Name - **Delivery of Google Kubernetes Engine (GKE) Service for GCP including Security Command Center**

The name of the service.
- [ ] Service Approval Accelerator Definition - **Relates to PR** #48

The written definition of a compliant service, including security, regulatory and quality standards for that service.
- [ ] Define Control Framework with Test Case definition

Test cases to be created to prove the integrity of the given service. These tests will form the service controls.
- [ ] Deployment Scripts Created

Terraform or YAML scripts to provision resources in keeping with the control framework.
- [ ] Gherkin Scripts Created

BDD feature scripts that map the defined test cases onto the control framework.

**Comment by mcleo-d** [comment]
@pudern and @alfredtommy - Thanks so much for raising this issue. I have added to the CSC kanban and have updated the status to `In Progress`.

Before I share the issue with the CSC group, can you update the issue to include the answer to the following task. This will make the issue easier to share with the group. 

`Decide on a single GCP service use case that's similar to current CSC AWS and Azure focus

Thanks for your ongoing support 👍 

James

**Comment by mcleo-d** [comment]
Hi @alfredtommy, 

Thanks for the update you sent me over email today. 

I have updated the issue title to ... 
* **Delivery of Google Kubernetes Engine (GKE) Service for GCP including Security Command Center**.

I have also added the following item to the issue body ...
* Contribution to focus on **Google Kubernetes Engine (GKE)** Service - https://cloud.google.com/kubernetes-engine/docs/concepts/kubernetes-engine-overview`

I will now email the CSC group to inform them of the issue and call for feedback. In the meantime, feel free to amend the text I have added if details need to be added or updated.

James.

**Comment by mcleo-d** [comment]
@pudern and @alfredtommy - The Cloud Service Certification agenda for 2nd July has been created in the project GitHub Issues #45 and it would be great if you could bring an update of this work item to the group. 

Please comment on #45 what you would like me and the team to add.

Also, FINOS has a Board of Directors quarterly meeting on 15th July where there will be a CSC project update, so it would be great if a PR of this work item #44 is raised prior to this date 😀  

James.

**Comment by mcleo-d** [comment]
**New Cloud Service** acceptance criteria added to issue following acceptance of #46 that delivers https://github.com/finos/cloud-service-certification/issues/new?template=Cloud_service.md
