### ISSUE TITLE
Nomination of Peter Thomas from Deutsche Bank as Cloud Service Certification Lead Maintainer

### ISSUE THREAD

**Issue by alfredtommy** [finos/cloud-service-certification#54]
Although I haven't had the privilege of directly working with Peter, I do believe he is the best fit for the Cloud Service Certification Lead Maintainer given his pedantry and his insights..

**Comment by mcleo-d** [comment]
Hi @alfredtommy 

Thank you for nominating @peterrhysthomas as Lead Maintainer for Cloud Service Certification. I will circulate with the project and add to the next meeting agenda to gather group feedback and consensus.

Kind regards,

James.

**Comment by leefaus** [comment]
In my short time getting to know  @peterrhysthomas I would recommend him for this role.

**Comment by mcleo-d** [comment]
This issue is now closed after the Cloud Service Certification project approved @peterrhysthomas as Lead Maintainer in the 13th August project meeting #56

**Comment by maoo** [comment]
FINOS metadata updated accordingly, /cc @mcleo-d
