### ISSUE TITLE
Update Cloud Service Certification GitHub Team Members

### ISSUE THREAD

**Issue by mcleo-d** [finos/cloud-service-certification#58]
## Description
This issue describes changes to be made by @maoo at FINOS to the Cloud Service Certification team in GitHub now Peter Thomas (@peterrhysthomas) from Deutsche Bank has been approved as the CSC Lead Maintainer. See #54 #56  

The changes below should happen to the following team https://github.com/orgs/finos/teams/fdx-cloud-cert/members

## Action Items 
1. Add Peter Thomas as **Lead Maintainer** (@peterrhysthomas) to Cloud Service Certification.
2. Remove Jason Nelson (@git-hub-forwork1) from the Cloud Service Certification GitHub team until further notice.  
3. Remove Rob Underwood (@brooklynrob) from the Cloud Service Certification GitHub team until further notice. 
4. No change to Abdullah Garcia (@abdullahgarcia) from JPMC.

**Comment by maoo** [comment]
All items above were done, plus:

5. Marked @peterrhysthomas as "Maintainer" of the Team, as he's the lead maintainer, he can choose who's part of the maintainers team and who doesn't
6. Renamed team to `cloud-cert-maintainers` (was `fdx-cloud-cert`)
