### ISSUE TITLE
Define the Service Approval Accelerator for Kubernetes on Azure

### ISSUE THREAD

**Issue by tmewett** [finos/cloud-service-certification#68]
### Description

Define the Service Approval Accelerator for Kubernetes using the Service Approval Accelerator Template for reference.

### Tasks

- [ ] Write and commit an Accelerator as `azure/kubernetes.md`

**Comment by iantivey** [comment]
The CIS GKE Benchmark has recommendations that are easily transposable to AKS:
https://cloud.google.com/kubernetes-engine/docs/concepts/cis-benchmarks#accessing-gke-benchmark

**Comment by iantivey** [comment]
Misconfiguring ManagedPodIdentities is something that can result in an identity attack surface. This article highlights the issues:
https://itnext.io/using-aad-pod-identity-in-your-azure-kubernetes-clusters-what-to-watch-out-for-73d5d73960f

**Comment by mcleo-d** [comment]
Hi @TLATER 

I thought I'd introduce you to this issue `Define the Service Approval Accelerator for Kubernetes on Azure #68` as it directly relates to the work being done in PR #72.

Kind regards,

James.
