### ISSUE TITLE
Addition of IaaC (Terraform Scripts) for GKE service

### ISSUE THREAD

**Issue by alfredtommy** [finos/cloud-service-certification#69]
## GKE Terraform Script

- Cloud Platform Target: GCP

- The directory in which the Cloud Service will reside (/gcp/gke).

- The name of the service: IaaC (Terraform) for GKE

Description: Tested and validated terraform script(s) for deployment of GKE cluster and node pools as per security and networking best practices.

**Comment by mcleo-d** [comment]
Hi @alfredtommy - Thanks for opening and closing this issue. It would be great to comment on why the issue was closed just to keep track of the reasoning 👍
