### ISSUE TITLE
Simplifying Cloud Service Certification On-boarding and Project Information

### ISSUE THREAD

**Issue by mcleo-d** [finos/cloud-service-certification#7]
It's been reported that on-boarding into the Cloud Service Certification working group can be confusing and disjointed. 

For example, if you Google "FINOS Cloud Certification" you will most likely land on the GitHub page: 
[https://github.com/finos/cloud-service-certification](https://github.com/finos/cloud-service-certification)

However, much of the important background information is found on the following Confluence page which the GitHub project doesn't link to:
[https://finosfoundation.atlassian.net/wiki/spaces/FDX/pages/904626436/Cloud+Service+Certification+Project](https://finosfoundation.atlassian.net/wiki/spaces/FDX/pages/904626436/Cloud+Service+Certification+Project)

Discovering relevant information about the project, meetings, mailing lists, locating the code and wiki can be a challenge.

The potential resolution to this issue is to migrate related group information into the GitHub Cloud Service Certification repository and make sure all references and links point to GitHub. 

This makes sure all related project information is together in a single place and is also good for Google which tends to point to the GitHub repo when searching the project.

It would be good to get further comments and thoughts from the Cloud Service Certification group before a decision to action is made.

**Comment by jbjonesjr** [comment]
As more of the Foundation's assets and front door are moving to :octocat: , i'd advocate for at least mirroring the key information here, if not deprecating the confluence pieces all together.

But that's just my opinion.

**Comment by mcleo-d** [comment]
Just as an update, I've started adding content from the FINOS wiki on Confluence to the Cloud Service Certification wiki on GitHub. Feel free to review the first page below.

https://github.com/finos/cloud-service-certification/wiki/Cloud-Service-Certification-Project

**Comment by mcleo-d** [comment]
The following pages have been migrated from the FINOS Wiki to the GitHub Wiki

-  [Open Volunteer Roles](https://finosfoundation.atlassian.net/wiki/spaces/FDX/pages/1178206217/Open+Volunteer+Roles)
-  [Compliance Framework Mapping Role](https://finosfoundation.atlassian.net/wiki/spaces/FDX/pages/1178271750/Compliance+Framework+Mapping+Role)
-  [Cloud Service Certification Documentation Role](https://finosfoundation.atlassian.net/wiki/spaces/FDX/pages/1178402847/Cloud Service Certification Documentation Role)
- [Codified Controls Development Role](https://finosfoundation.atlassian.net/wiki/spaces/FDX/pages/1178239029/Codified+Controls+Development+Role)
-  [BDD Test Case Development Role](https://finosfoundation.atlassian.net/wiki/spaces/FDX/pages/1178206230/BDD+Test+Case+Development+Role)
-  [Cloud Service Effort Owner](https://finosfoundation.atlassian.net/wiki/spaces/FDX/pages/1178304603/Cloud+Service+Effort+Owner)
-  [Peer Reviewer Role](https://finosfoundation.atlassian.net/wiki/spaces/FDX/pages/1178271767/Peer+Reviewer+Role)

The following page still needed a deprecated label before the task can be completed
- [Cloud Service Certification Project](https://finosfoundation.atlassian.net/wiki/spaces/FDX/pages/904626436/Cloud+Service+Certification+Project)

**Comment by mcleo-d** [comment]
All pages have now been migrated to GitHub Wiki including ...

- [Cloud Service Certification Project](https://finosfoundation.atlassian.net/wiki/spaces/FDX/pages/904626436/Cloud+Service+Certification+Project)
