### ISSUE TITLE
5 November 2020 - Cloud Service Certification Meeting

### ISSUE THREAD

**Issue by mcleo-d** [finos/cloud-service-certification#78]
## Date
Thursday 5 November 2020 - 12pm EST / 5pm UK

## Untracked attendees
| Name | Firm | Comment |
|:---------|:------------|:-----|

## Agenda

- [x] Convene, roll call, welcome new people
- [x] Approve previous meeting minutes - https://github.com/finos/cloud-service-certification/issues?
- [x] Cloud Service Certification [Project Kanban](https://github.com/orgs/finos/projects/1q=is%3Aissue+is%3Aclosed+label%3Ameeting) Review
  - Including @alfredtommy pull request review of GKE TF scripts #73 outcome from **Wednesday 4th November @ 2pm UK / 9am ET** 
- [x] Introduction from [EDMC](https://edmcouncil.org/) and [CDMC](https://edmcouncil.org/page/CDMC) team - **Oli Bage** (Refinitiv) & **Richard Perris** (Morgan Stanley)
- [x] Walk through of 'ready to consume' CDMC policy - **Oli Bage** & **Richard Perris**
  - Comparison to existing CSC Service Accelerator Template - @peterrhysthomas to chair
- [x] AOB, Q&A & Adjourn (5mins)

## Previous Action Updates
- [ ] @eddie-knight to form an opinion and report the viability of Pulumi and BDD Tests #62 including @leefaus & @alfredtommy
- [ ] @tmewett to move forward with Consider Asciidoc for document markup #70 by combining with #72 if viable and appropriate.

### WebEx info
**Webex:** 
https://finos.webex.com/finos/j.php?MTID=m4b7c03efc2237c6685c1846e6d815cc3

**Dial-in**
**US** +1-415-655-0003 US Toll
**UK** +44-20319-88141 UK Toll
**Access code:** 127 062 3555

**Github Repo:** https://github.com/finos/cloud-service-certification/
**Project Wiki Page:** https://finosfoundation.atlassian.net/wiki/spaces/FDX/pages/904626436/Cloud+Service+Certification+Project

**Comment by abdullahgarcia** [comment]
+1

**Comment by mcleo-d** [comment]
Hi there 👋

**Comment by peterrhysthomas** [comment]
hello

**Comment by anthonygtech** [comment]
Hello

**Comment by J0EG** [comment]
Hello

**Comment by alfredtommy** [comment]
hello

**Comment by abdullahgarcia** [comment]
¡Hola!

**Comment by danizheleva** [comment]
Hello

**Comment by cr20ro20** [comment]
hello from Craig

**Comment by ojeb2** [comment]
Hello

**Comment by eddie-knight** [comment]
:wave: :shipit:
