### ISSUE TITLE
3 December 2020 - Cloud Service Certification Meeting

### ISSUE THREAD

**Issue by mcleo-d** [finos/cloud-service-certification#85]
## Date
Thursday 3 December 2020 - 10am EST / 3pm GMT

## Untracked attendees
| Name | Firm | Comment |
|:---------|:------------|:-----|

## Agenda

- [x] Convene, roll call, welcome new people
- [x] Approve previous meeting minutes - https://github.com/finos/cloud-service-certification/issues?q=is%3Aissue+is%3Aclosed+label%3Ameeting
- [x] Cloud Service Certification [Project Kanban](https://github.com/orgs/finos/projects/1) Review
  - [x] @abdullahgarcia and @peterrhysthomas update on PR #76 review - **Service Accelerator Template for EKS (Kubernetes) on Amazon AWS**
  - [x] Update on **CIS benchmarks and BDD Discussion** https://github.com/finos/cloud-service-certification/issues/84#issuecomment-734428024 with @leefaus, @alfredtommy, Paul Jones, @erictice, @abdullahgarcia, @jamilmina1 and @eddie-knight
- [x] @mcleo-d brief update on Cloudify meeting with @peterrhysthomas, @natishalom and @alexmolev
- [x] AOB, Q&A & Adjourn (5mins)

## Decisions Made
- [ ] Decision 1
- [ ] Decision 2
- [ ] ...

## Action Items
- [ ] Action 1
- [ ] Action 2
- [ ] ...

### WebEx info
**Webex:** 
https://finos.webex.com/finos/j.php?MTID=m4b1d85127d1f3ca179545d6bd3291975

**Dial-in**
**US** +1-415-655-0003 US Toll
**UK** +44-20319-88141 UK Toll
**Access code:** 127 846 2278

**Github Repo:** https://github.com/finos/cloud-service-certification/
**Project Wiki Page:** https://finosfoundation.atlassian.net/wiki/spaces/FDX/pages/904626436/Cloud+Service+Certification+Project 
**Mailing List:** Email fdx-cloud-service-certification+subscribe@finos.org to subscribe to our mailing list

**Comment by fleadsom** [comment]
Hello! 🤓

**Comment by erictice** [comment]
Hello

**Comment by J0EG** [comment]
Morning from NY

**Comment by mcleo-d** [comment]
Remember to say hello in the comments 👍

**Comment by peterrhysthomas** [comment]
hello

**Comment by eddie-knight** [comment]
:wave: :shipit:

**Comment by mcleo-d** [comment]
Nice use of the hamster @eddie-knight 😀

**Comment by abdullahgarcia** [comment]
¡Hola!

**Comment by TLATER** [comment]
o/

**Comment by git-hub-forwork1** [comment]
back from Coventry

**Comment by adamj-codethink** [comment]
:wave:

**Comment by leefaus** [comment]
here 👀  🚢  :shipit:

**Comment by brooklynrob** [comment]
here

**Comment by mcleo-d** [comment]
@cr20ro20 it would be great if you could say hello in the comments to be added to the CSC meeting roll call 👍
