### ISSUE TITLE
Error thrown whilst running meeting-minutes-action

### ISSUE THREAD

**Issue by mcleo-d** [finos/cloud-service-certification#87]
## Error thrown whilst running meeting-minutes-action

The following error is thrown whilst running the `meeting-minutes-action` GitHub Action that automates the registration of people attending Cloud Service Certification project meetings.

## Error Outcome
- no `index` label 
- no comment highlighting new attendees.

## Error Thrown
https://github.com/finos/cloud-service-certification/runs/1517884793

![Screenshot 2020-12-08 at 14 34 02](https://user-images.githubusercontent.com/6029572/101497274-b4ede580-3962-11eb-9455-ddd3a62db138.png)

**Comment by maoo** [comment]
Fixed, see https://github.com/finos/cloud-service-certification/issues/85#issuecomment-744044452
