### ISSUE TITLE
17 December 2020 - Cloud Service Certification Meeting

### ISSUE THREAD

**Issue by mcleo-d** [finos/cloud-service-certification#88]
## Date
Thursday 17 December 2020 - 10am EST / 3pm GMT

## Untracked attendees
| Name | Firm | Comment |
|:---------|:------------|:-----|

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [ ] Convene, roll call, welcome new people (5mins)
- [ ] Display [FINOS Antitrust Policy summary slide](https://github.com/finos/community/blob/master/governance/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [ ] Review Meeting Notices (see above)
- [ ] Approve previous meeting minutes - https://github.com/finos/cloud-service-certification/issues?q=is%3Aissue+is%3Aclosed+label%3Ameeting
- [ ] Cloud Service Certification [Project Kanban](https://github.com/orgs/finos/projects/1) Review
- [ ] _Add Items Here_
- [ ] AOB, Q&A & Adjourn (5mins)

## Decisions Made
- [ ] Decision 1
- [ ] Decision 2
- [ ] ...

## Action Items
- [ ] Action 1
- [ ] Action 2
- [ ] ...

### WebEx info
**Webex:** 
https://finos.webex.com/finos/j.php?MTID=m4b1d85127d1f3ca179545d6bd3291975

**Dial-in**
- **US** +1-415-655-0003 US Toll
- **UK** +44-20319-88141 UK Toll
- **Access code:** 127 846 2278

**Github Repo:** https://github.com/finos/cloud-service-certification/

**Project Wiki Page:** https://finosfoundation.atlassian.net/wiki/spaces/FDX/pages/904626436/Cloud+Service+Certification+Project 

**Mailing List:** Email fdx-cloud-service-certification+subscribe@finos.org to subscribe to our mailing list

**Comment by leefaus** [comment]
:wave: 🎁 🎉

**Comment by eddie-knight** [comment]
:wave: :shipit:

**Comment by adamj-codethink** [comment]
![tenor](https://user-images.githubusercontent.com/45950887/102504756-215e9800-4079-11eb-9e05-0cd173c776ee.gif)

**Comment by jamilmina1** [comment]
hi

**Comment by mcleo-d** [comment]
Hi all - Happy holidays 🎄

**Comment by fleadsom** [comment]
Hey!

**Comment by peterrhysthomas** [comment]
Hi all

**Comment by anthonygtech** [comment]
Hello.

**Comment by alfredtommy** [comment]
Hello

**Comment by abdullahgarcia** [comment]
¡Hola!
