### ISSUE TITLE
14 January 2021 - Cloud Service Certification Meeting

### ISSUE THREAD

**Issue by mcleo-d** [finos/cloud-service-certification#89]
## Date
Thursday 14 January 2021 - 10am EST / 3pm GMT

## Untracked attendees
| Name | Firm | Comment |
|:---------|:------------|:-----|

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene, roll call, welcome new people (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://github.com/finos/community/blob/master/governance/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [x] Approve previous meeting minutes - https://github.com/finos/cloud-service-certification/issues?q=is%3Aissue+is%3Aclosed+label%3Ameeting
- [x] Cloud Service Certification [Project Kanban](https://github.com/orgs/finos/projects/1) Review
- [ ] AOB, Q&A & Adjourn (5mins)

## Actions
- This is to confirm the meeting scheduled to review Add Azure Kubernetes Service Approval Accelerator #90 with @TLATER and the CSC project prior to accepting the PR - https://github.com/finos/cloud-service-certification/pull/90#issuecomment-765326697
  - Topic: FINOS CSC - Review : Add Azure Kubernetes Service Approval Accelerator #90
  - Time: Jan 22, 2021 3:00 PM GMT / 10:00AM ET
  - Join Zoom Meeting - https://github.com/finos/cloud-service-certification/pull/90#issuecomment-765326697
    - https://zoom.us/j/92304379984

### WebEx info
**Webex:** 
https://finos.webex.com/finos/j.php?MTID=m4b1d85127d1f3ca179545d6bd3291975

**Dial-in**
- **US** +1-415-655-0003 US Toll
- **UK** +44-20319-88141 UK Toll
- **Access code:** 127 846 2278

**Github Repo:** https://github.com/finos/cloud-service-certification/

**Project Wiki Page:** https://finosfoundation.atlassian.net/wiki/spaces/FDX/pages/904626436/Cloud+Service+Certification+Project 

**Mailing List:** Email fdx-cloud-service-certification+subscribe@finos.org to subscribe to our mailing list

**Comment by leefaus** [comment]
👋🏻  HNY 🎉

**Comment by jamilmina1** [comment]
hi

**Comment by J0EG** [comment]
Happy New Year and Good Morning from NY.

**Comment by eddie-knight** [comment]
👋 :shipit:

**Comment by danizheleva** [comment]
Hello and happy new year 🎉

**Comment by mcleo-d** [comment]
Hello 👋

**Comment by abdullahgarcia** [comment]
¡Hola!

**Comment by adds68** [comment]
Hey Hey :wave:

**Comment by cr20ro20** [comment]
Hi

**Comment by fleadsom** [comment]
Hey 🌚

**Comment by mcleo-d** [comment]
Hi @adds68,

I have added your @adds68 GitHub profile to our internal records alongside @adamj-codethink 👍 

cc @aitana16 and @maoo

**Comment by adds68** [comment]
Thanks @mcleo-d! After 8 years i finally got my old github name back! :partying_face:
