### ISSUE TITLE
28 January 2021 - Cloud Service Certification Meeting

### ISSUE THREAD

**Issue by mcleo-d** [finos/cloud-service-certification#93]
## Date
Thursday 28 January 2021 - 10am EST / 3pm GMT

## Untracked attendees
| Name | Firm | Comment |
|:---------|:------------|:-----|

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene, roll call, welcome new people (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://github.com/finos/community/blob/master/governance/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [x] Approve previous meeting minutes - https://github.com/finos/cloud-service-certification/issues?q=is%3Aissue+is%3Aclosed+label%3Ameeting
- [x] @mindthegab - Update Cloud Service Certification on recent EDMC conversations
- [x] @peterrhysthomas & @mcleo-d - Discuss **Project Maintainer** and **Project Coordinator** roles with the CSC group
- [x] Cloud Service Certification [Project Kanban](https://github.com/orgs/finos/projects/1) Review
- [ ] _Add Items Here_
- [x] AOB, Q&A & Adjourn (5mins)
  - 🙌  💯 💯 💯 - @eddie-knight from CitiHub representing the Cloud Service Certification GCP / GKE journey at the [FINOS All Community Call](https://www.linkedin.com/feed/update/urn:li:activity:6760209680775057409) 

### WebEx info
**Webex:** 
https://finos.webex.com/finos/j.php?MTID=m4b1d85127d1f3ca179545d6bd3291975

**Dial-in**
- **US** +1-415-655-0003 US Toll
- **UK** +44-20319-88141 UK Toll
- **Access code:** 127 846 2278

**Github Repo:** https://github.com/finos/cloud-service-certification/

**Project Wiki Page:** https://finosfoundation.atlassian.net/wiki/spaces/FDX/pages/904626436/Cloud+Service+Certification+Project 

**Mailing List:** Email fdx-cloud-service-certification+subscribe@finos.org to subscribe to our mailing list

**Comment by mcleo-d** [comment]
👋  - Hello!

**Comment by TLATER** [comment]
o/

**Comment by erictice** [comment]
Hello

**Comment by daniela-g-zheleva-db** [comment]
Hello 👍

**Comment by eddie-knight** [comment]
:wave: :shipit:

**Comment by peterrhysthomas** [comment]
Hi all

**Comment by leefaus** [comment]
Howdy y'all! 👯

**Comment by fleadsom** [comment]
hi :)

**Comment by mceciliafernandes** [comment]
Hi!
